# Generated by Django 3.2.9 on 2021-12-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=2, upload_to='photo/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
