# Generated by Django 3.2.9 on 2021-12-10 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloger', '0002_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
