# Generated by Django 3.2.9 on 2021-12-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloger', '0003_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='nameauthor',
            field=models.CharField(default='author', max_length=30),
        ),
    ]
