# Generated by Django 3.2.9 on 2021-12-11 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloger', '0004_post_nameauthor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='nameauthor',
        ),
    ]
