# Generated by Django 3.2.9 on 2021-12-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloger', '0007_rename_comment_commentblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentblog',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='commentblog',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
