# Generated by Django 3.2.9 on 2021-12-12 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloger', '0008_auto_20211212_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentblog',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='commentblog',
            name='date_updated',
        ),
    ]
