# Generated by Django 3.2.9 on 2021-12-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloger', '0010_commentblog_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.CharField(default=1, max_length=22),
            preserve_default=False,
        ),
    ]
