# Generated by Django 3.2.9 on 2021-12-14 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloger', '0011_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentblog',
            name='email',
        ),
    ]
