# Generated by Django 3.2.9 on 2021-12-08 04:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('category', models.CharField(choices=[('word', 'Word'), ('technogoly', 'Technogoly'), ('design', 'Design'), ('culture', 'Culture'), ('business', 'Business'), ('word1', 'Word1'), ('technogoly1', 'Technogoly1'), ('design1', 'Design1'), ('culture1', 'Culture1'), ('business1', 'Business1')], default='word', max_length=50)),
                ('thumbnall', models.ImageField(upload_to='photo/%Y/%m/%d/')),
                ('excerpt', models.CharField(max_length=150)),
                ('month', models.CharField(max_length=3)),
                ('day', models.CharField(max_length=2)),
                ('content', models.TextField()),
                ('featured', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
