# Generated by Django 3.2.9 on 2021-12-08 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogfabbi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('event', 'Event'), ('recruitment', 'Recruitment'), ('fabbi hanoi', 'Fabbi Hanoi'), ('media', 'Media')], default='event', max_length=50),
        ),
    ]
