# Generated by Django 3.2.9 on 2021-12-05 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('category', models.CharField(choices=[('html', 'Html'), ('python', 'Python'), ('react', 'React'), ('java', 'Java'), ('javascript', 'Javascript'), ('c', 'C'), ('c++', 'C1'), ('c#', 'C2'), ('ruby', 'Ruby'), ('django', 'Django')], default='html', max_length=50)),
                ('thumbnall', models.ImageField(upload_to='photo/%Y/%m/%d/')),
                ('excerpt', models.CharField(max_length=150)),
                ('month', models.CharField(max_length=3)),
                ('day', models.CharField(max_length=2)),
                ('content', models.TextField()),
                ('featured', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('source', models.CharField(max_length=50)),
            ],
        ),
    ]
