# Generated by Django 3.2.9 on 2021-12-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_it', '0002_remove_blogpost_thumbnall'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
