# Generated by Django 3.2.9 on 2021-12-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_it', '0003_blogpost_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='viewCount',
            field=models.IntegerField(default=0),
        ),
    ]
